# Generated by Django 3.2.2 on 2021-06-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datePosted',
            new_name='date_posted',
        ),
    ]
